### ISSUE TITLE
Include client and target git commit id in collected data set

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh_diag#10]
Please add a method for collecting the NVMesh-{client,target} git commit ID.  This data is stored in a version file under /proc/nvmeib[cs]

Example:
```
# cat /proc/nvmeibc/version
NVMesh f72a3d

# cat /proc/nvmeibs/version
NVMesh f72a3d
```

**Comment by excelero-andreas** [comment]
OK - next iteration

**Comment by excelero-andreas** [comment]
nvmeshdiag now reports the nvmesh package details including version numbers.
