### ISSUE TITLE
No prompt to set ONE_QP_PER_RECOVERY with '-s' option

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh_diag#2]
With SLES 12 SP3, while using the tool to set the known best-practices, it was noted that the adapter firmware option for RDDA on MLX5-based systems was not set.  The tool did not offer to set it for us either.

**Comment by excelero-andreas** [comment]
Just jumped over the code. This feature is not built in currently. Will work on it.

**Comment by excelero-andreas** [comment]
It's in the code now. The dev and test code branch is set-one-qp-per-recovery.
Need help with testing though

**Comment by excelero-andreas** [comment]
Tested and verified that it works.
